-- Top 10 most-rented movies

SELECT 
    f.title,
	c.name AS category,
    COUNT(r.rental_id) AS movie_rental_count
FROM 
    film f
INNER JOIN 
    inventory i 
    ON f.film_id = i.film_id
INNER JOIN 
    rental r 
    ON i.inventory_id = r.inventory_id
INNER JOIN 
    film_category fc 
	ON f.film_id = fc.film_id
INNER JOIN 
    category c 
	ON fc.category_id = c.category_id  
GROUP BY 
    f.film_id, f.title,c .name
ORDER BY 
    movie_rental_count DESC
LIMIT 10

-- INSIGHT: The most-rented movies are predominantly Travel and Foreign titles, indicating a customer preference for culturally rich or globally themed content.


-- Top 5 most popular film categories

SELECT * FROM 
(SELECT 
    c.name, 
    COUNT(fc.film_id) AS count_of_film_categories,
    DENSE_RANK() OVER (ORDER BY COUNT(fc.film_id) DESC) AS category_rank
FROM 
    film f
INNER JOIN 
    film_category fc ON f.film_id = fc.film_id
INNER JOIN 
    category c ON fc.category_id = c.category_id
GROUP BY 
    c.name
ORDER BY 
    category_rank)
	WHERE category_rank BETWEEN 1 AND 5

-- INSIGHT: Sports remains the most popular film category, followed closely by Foreign and Family, suggesting a demand for fast-paced and thrilling genres


-- Revenue Generated by Each Film Category

SELECT 
    c.name AS category,
    SUM(p.amount) AS total_revenue
FROM 
    payment p
JOIN 
    rental r ON p.rental_id = r.rental_id
JOIN 
    inventory i ON r.inventory_id = i.inventory_id
JOIN 
    film f ON i.film_id = f.film_id
JOIN 
    film_category fc ON f.film_id = fc.film_id
JOIN 
    category c ON fc.category_id = c.category_id
GROUP BY 
    c.name
ORDER BY 
    total_revenue DESC

--Sports, Sci-Fi, Animation, and Drama are the top revenue-generating categories, reflecting a strong customer appetite for both high-adrenaline and emotionally engaging storytelling.
